#!/bin/bash
platform=$(/usr/local/bin/nems-info platform)
export PIP_ROOT_USER_ACTION=ignore

npm install -g speed-cloudflare-cli

## Allow nagios and users in nagios group (your NEMS user) to run root nems-info commands without a password

# nems-info undervoltage
if ! grep -q "%nagios ALL=NOPASSWD: /usr/bin/vcgencmd" /etc/sudoers; then
  echo '%nagios ALL=NOPASSWD: /usr/bin/vcgencmd' | sudo EDITOR='tee -a' visudo
fi

############################################################################################################

# Ensure Python is not set to Externally Managed
for pythondir in /usr/lib/python*/; do
  if [ -f "$pythondir/EXTERNALLY-MANAGED" ]; then
    rm "$pythondir/EXTERNALLY-MANAGED"
    echo "$pythondir was set to Externally managed. Changed."
  fi
done

# DHTxx support for Raspberry Pi
if (( $platform >= 0 )) && (( $platform <= 9 )) || (( $platform >= 150 )) && (( $platform <= 199 )); then
  # 'board' module
  pip3 install adafruit-blinka
  # dht module
  pip3 install adafruit-circuitpython-dht

  # Setup User access
  adduser nagios gpio
  adduser nemsadmin gpio

  # Avoid errors if the user is already part of the GPIO group
  echo ""
fi

# Set permissions
  # nems-userctl
  chown root:root /usr/local/sbin/nems-userctl
  chmod 750 /usr/local/sbin/nems-userctl
